/**
 * lib/export/pdf-html.ts
 * Builds a branded HTML string for Skatteverket-ready körjournal PDF.
 * The web variant opens the HTML in a new window and triggers window.print().
 */
import type { CustomTag, ExportMoneyOptions, ExportTier, VehicleInfo, WebTripRow } from "./types";
import { applyDecSep, buildRow, buildSummary, columnLabels, tierColumns } from "./data";

const PAGE_STYLE = `
  @page { margin: 18mm 14mm; }
  @media print { body { print-color-adjust: exact; -webkit-print-color-adjust: exact; } }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; font-size: 9pt; color: #111; background: #fff; }
  .header { border-bottom: 2px solid #E31E26; padding-bottom: 8pt; margin-bottom: 12pt; }
  .header-title { font-size: 18pt; font-weight: 700; color: #E31E26; letter-spacing: -0.5pt; }
  .header-meta { font-size: 8pt; color: #666; margin-top: 4pt; }
  .summary-box { background: #f7f7f7; border-radius: 6pt; padding: 10pt 14pt; margin-bottom: 14pt; display: flex; flex-wrap: wrap; gap: 24pt; }
  .summary-item { }
  .summary-label { font-size: 7pt; color: #888; text-transform: uppercase; letter-spacing: 0.5pt; }
  .summary-value { font-size: 13pt; font-weight: 700; color: #111; margin-top: 1pt; }
  .summary-sub { font-size: 7.5pt; color: #555; margin-top: 1pt; }
  .section-title { font-size: 7pt; text-transform: uppercase; letter-spacing: 1pt; color: #999; margin-bottom: 4pt; font-weight: 600; }
  table { width: 100%; border-collapse: collapse; font-size: 7.5pt; }
  thead tr { background: #E31E26; color: #fff; }
  thead th { padding: 4pt 5pt; text-align: left; font-weight: 600; white-space: nowrap; font-size: 7pt; }
  tbody tr:nth-child(even) { background: #fafafa; }
  tbody tr:nth-child(odd)  { background: #fff; }
  tbody td { padding: 3.5pt 5pt; border-bottom: 0.5pt solid #eee; vertical-align: top; }
  .tag-work     { color: #30D158; font-weight: 600; }
  .tag-commute  { color: #0A84FF; font-weight: 600; }
  .tag-personal { color: #FF9F0A; }
  .tag-untagged { color: #999; }
  .footer { margin-top: 16pt; padding-top: 8pt; border-top: 0.5pt solid #ddd; font-size: 7pt; color: #999; }
  .legal { margin-top: 4pt; font-size: 6.5pt; color: #bbb; }
  .warning-box { background: #FFF3CD; border: 1pt solid #FFC107; border-radius: 4pt; padding: 6pt 10pt; margin-bottom: 10pt; font-size: 8pt; color: #856404; }
`;

function tagClass(tag: string): string {
  switch (tag) {
    case "work":     return "tag-work";
    case "commute":  return "tag-commute";
    case "personal": return "tag-personal";
    default:         return "tag-untagged";
  }
}

function fmtKm(n: number, unit: "km" | "mi" = "km", opts?: ExportMoneyOptions): string {
  const numLocale = opts?.decimalSeparator === "." ? "en-US" : "sv-SE";
  const dist = unit === "mi" ? n * 0.621371 : n;
  return dist.toLocaleString(numLocale, { minimumFractionDigits: 1, maximumFractionDigits: 1 }) + " " + unit;
}

function fmtMoney(kr: number, opts?: ExportMoneyOptions): string {
  const numLocale = opts?.decimalSeparator === "." ? "en-US" : "sv-SE";
  return kr.toLocaleString(numLocale, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + " kr";
}

export function buildPDFHTML(
  trips: WebTripRow[],
  tier: ExportTier,
  milersattningPerKm: number,
  vehicle: VehicleInfo | null,
  label: string,
  userName: string,
  reviewWarningCount: number,
  opts?: ExportMoneyOptions,
  customTags?: CustomTag[],
): string {
  const cols    = tierColumns(tier);
  const summary = buildSummary(trips, milersattningPerKm, customTags);
  const labels  = columnLabels(opts);
  const locale  = opts?.locale ?? "sv-SE";
  const unit    = opts?.distanceUnit ?? "km";
  const isEn    = locale.toLowerCase().startsWith("en");

  const now = new Date();
  const generatedDate = now.toLocaleDateString(locale, { year: "numeric", month: "long", day: "numeric" });

  const T = isEn ? {
    title: "Drive Log",
    level: "Level",
    generated: "Generated",
    totalTrips: "Total trips",
    totalDist: "Total distance",
    workKm: "Work km",
    reimbursement: "Mileage reimbursement",
    totalEnergy: "Total energy",
    tripsSection: "Trips",
    reviewWarning: (count: number) => `${count} trip${count !== 1 ? "s" : ""} need review and have been excluded from this export.`,
    generatedBy: (user: string, period: string) => `Generated by ${user} · ${period}`,
    legal: (rate: number) => `Mileage reimbursement: ${rate.toFixed(2)} kr/km (Skatteverket standard 2025).`,
    tierNames: { skatteverket: "Skatteverket", standard: "Standard", fullstandig: "Complete" } as Record<ExportTier, string>,
  } : {
    title: "Körjournal",
    level: "Nivå",
    generated: "Genererad",
    totalTrips: "Totalt resor",
    totalDist: "Totalt avstånd",
    workKm: "Tjänstekm",
    reimbursement: "Milersättning",
    totalEnergy: "Total energi",
    tripsSection: "Resor",
    reviewWarning: (count: number) => `${count} resa${count !== 1 ? "r" : ""} kräver granskning och har exkluderats från denna export.`,
    generatedBy: (user: string, period: string) => `Genererad av ${user} · ${period}`,
    legal: (rate: number) => `Milersättning beräknad enligt Skatteverkets schablon ${rate.toFixed(2)} kr/km (2025).`,
    tierNames: { skatteverket: "Skatteverket", standard: "Standard", fullstandig: "Fullständig" } as Record<ExportTier, string>,
  };

  // Summary box
  const summaryItems: { label: string; value: string; sub?: string }[] = [
    { label: T.totalTrips, value: String(summary.totalTrips) },
    { label: T.totalDist,  value: fmtKm(summary.totalKm, unit, opts) },
    {
      label: T.workKm,
      value: fmtKm(summary.workKm, unit, opts),
      sub:   `${summary.workTrips} ${isEn ? "trip" : "resa"}${summary.workTrips !== 1 ? "s" : ""}`,
    },
    {
      label: T.reimbursement,
      value: fmtMoney(summary.milersattningKr, opts),
      sub:   `${milersattningPerKm.toFixed(2)} kr/km`,
    },
  ];
  if (summary.totalEnergyKwh != null) {
    summaryItems.push({
      label: T.totalEnergy,
      value: applyDecSep(summary.totalEnergyKwh.toFixed(1), opts?.decimalSeparator) + " kWh",
    });
  }

  const summaryHTML = summaryItems.map(s =>
    `<div class="summary-item"><div class="summary-label">${s.label}</div>` +
    `<div class="summary-value">${s.value}</div>` +
    (s.sub ? `<div class="summary-sub">${s.sub}</div>` : "") +
    `</div>`
  ).join("");

  const thHTML = cols.map(k => `<th>${labels[k] ?? k}</th>`).join("");

  const trHTML = trips.map(trip => {
    const row  = buildRow(trip, tier, milersattningPerKm, vehicle, opts, customTags);
    const cells = cols.map(k => {
      const val = row[k] ?? "";
      if (k === "Syfte") {
        return `<td><span class="${tagClass(trip.tag)}">${val}</span></td>`;
      }
      return `<td>${val}</td>`;
    }).join("");
    return `<tr>${cells}</tr>`;
  }).join("");

  const warningHTML = reviewWarningCount > 0
    ? `<div class="warning-box">&#9888; ${T.reviewWarning(reviewWarningCount)}</div>`
    : "";

  const lang = isEn ? "en" : "sv";

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${T.title} - ${label}</title>
<style>${PAGE_STYLE}</style>
</head>
<body>
<div class="header">
  <div class="header-title">${T.title}</div>
  <div class="header-meta">${userName} &nbsp;&bull;&nbsp; ${label} &nbsp;&bull;&nbsp; ${T.level}: ${T.tierNames[tier]} &nbsp;&bull;&nbsp; ${T.generated} ${generatedDate}</div>
</div>
${warningHTML}
<div class="summary-box">${summaryHTML}</div>
<div class="section-title">${T.tripsSection}</div>
<table>
  <thead><tr>${thHTML}</tr></thead>
  <tbody>${trHTML}</tbody>
</table>
<div class="footer">
  <div>${T.generatedBy(userName, label)}</div>
  <div class="legal">${T.legal(milersattningPerKm)}</div>
</div>
<script>window.onload = function() { window.print(); }</script>
</body>
</html>`;
}
