/**
 * lib/export/xlsx.ts
 * Builds an Excel workbook using SheetJS.
 * Sheet 1: "Körjournal"  — full trip table with styled header.
 * Sheet 2: "Sammanst."  — summary stats by tag.
 */
import * as XLSX from "xlsx";
import type { CustomTag, ExportMoneyOptions, ExportTier, VehicleInfo, WebTripRow } from "./types";
import { buildSummary, buildXlsxRow, columnLabels, NUMERIC_COL_FORMATS, tierColumns } from "./data";

function applyColumnFormats(
  ws: XLSX.WorkSheet,
  columns: readonly string[],
  formats: Record<string, string>,
  rowCount: number,
): void {
  for (let colIdx = 0; colIdx < columns.length; colIdx++) {
    const fmt = formats[columns[colIdx] as string];
    if (!fmt) continue;
    for (let r = 1; r <= rowCount; r++) {
      const ref = XLSX.utils.encode_cell({ r, c: colIdx });
      const cell = ws[ref];
      if (cell && typeof cell.v === "number") cell.z = fmt;
    }
  }
}

function setCellFormat(ws: XLSX.WorkSheet, addr: string, fmt: string): void {
  const cell = ws[addr];
  if (cell && typeof cell.v === "number") cell.z = fmt;
}

export function buildXLSX(
  trips: WebTripRow[],
  tier: ExportTier,
  milersattningPerKm: number,
  vehicle: VehicleInfo | null,
  periodLabel: string,
  userName: string,
  opts?: ExportMoneyOptions,
  customTags?: CustomTag[],
): Uint8Array {
  const cols    = tierColumns(tier);
  const summary = buildSummary(trips, milersattningPerKm, customTags);
  const labels  = columnLabels(opts);
  const isEn    = opts?.locale?.toLowerCase().startsWith("en");
  const moneyFmt = "#,##0.00";
  const distFmt  = "#,##0.0";
  const energyFmt = "0.00";

  // ── Sheet 1: Körjournal ───────────────────────────────────────
  const headerRowArr = cols.map(k => labels[k] ?? k);
  const dataRows = trips.map(trip =>
    cols.map(k => buildXlsxRow(trip, tier, milersattningPerKm, vehicle, opts, customTags)[k] ?? ""),
  );

  const ws1Data = [headerRowArr, ...dataRows];
  const ws1 = XLSX.utils.aoa_to_sheet(ws1Data);

  // Column widths
  const colWidths = cols.map(k => {
    if (k === "Startadress" || k === "Slutadress") return { wch: 40 };
    if (k === "Datum") return { wch: 12 };
    if (k === "Anteckning") return { wch: 30 };
    return { wch: 16 };
  });
  ws1["!cols"] = colWidths;

  // Apply numeric formats
  applyColumnFormats(ws1, cols, NUMERIC_COL_FORMATS, trips.length);

  // ── Sheet 2: Summary ──────────────────────────────────────────
  const T = isEn ? {
    period: "Period",
    generatedBy: "Generated by",
    reimbursementRate: "Reimbursement rate",
    category: "Category",
    trips: "Trips",
    distance: `Distance (${opts?.distanceUnit ?? "km"})`,
    reimbursement: "Reimbursement (kr)",
    work: "Work",
    commute: "Commute",
    personal: "Personal",
    untagged: "Untagged",
    total: "Total",
    totalEnergy: "Total energy (kWh)",
    totalCost: "Total electricity cost (kr)",
  } : {
    period: "Period",
    generatedBy: "Genererad av",
    reimbursementRate: "Milersättning",
    category: "Kategori",
    trips: "Resor",
    distance: `Avstånd (${opts?.distanceUnit ?? "km"})`,
    reimbursement: "Milersättning (kr)",
    work: "Tjänst",
    commute: "Pendling",
    personal: "Privat",
    untagged: "Otaggade",
    total: "Totalt",
    totalEnergy: "Total energi (kWh)",
    totalCost: "Total elkostnad (kr)",
  };

  const km = (n: number) =>
    opts?.distanceUnit === "mi" ? parseFloat((n * 0.621371).toFixed(1)) : parseFloat(n.toFixed(1));

  const summaryRows: (string | number)[][] = [
    [T.period,           periodLabel],
    [T.generatedBy,      userName],
    [T.reimbursementRate, milersattningPerKm + " kr/km"],
    [],
    [T.category, T.trips, T.distance, T.reimbursement],
    [T.work,     summary.workTrips,     km(summary.workKm),     parseFloat(summary.milersattningKr.toFixed(2))],
    [T.commute,  summary.commuteTrips,  km(summary.commuteKm),  ""],
    [T.personal, summary.personalTrips, km(summary.personalKm), ""],
  ];
  if (summary.untaggedTrips > 0) {
    summaryRows.push([T.untagged, summary.untaggedTrips, "", ""]);
  }
  summaryRows.push([]);
  summaryRows.push([T.total, summary.totalTrips, km(summary.totalKm), ""]);
  if (summary.totalEnergyKwh != null) {
    summaryRows.push([T.totalEnergy, parseFloat(summary.totalEnergyKwh.toFixed(2))]);
  }
  if (summary.totalCostKr != null) {
    summaryRows.push([T.totalCost, parseFloat(summary.totalCostKr.toFixed(2))]);
  }

  const ws2 = XLSX.utils.aoa_to_sheet(summaryRows);
  ws2["!cols"] = [{ wch: 28 }, { wch: 14 }, { wch: 16 }, { wch: 18 }];

  // Format numeric cells in summary sheet (rows 5–10ish, cols B-D)
  for (let r = 4; r < summaryRows.length; r++) {
    setCellFormat(ws2, XLSX.utils.encode_cell({ r, c: 1 }), "0");
    setCellFormat(ws2, XLSX.utils.encode_cell({ r, c: 2 }), distFmt);
    setCellFormat(ws2, XLSX.utils.encode_cell({ r, c: 3 }), moneyFmt);
  }
  if (summary.totalEnergyKwh != null) {
    const r = summaryRows.length - (summary.totalCostKr != null ? 2 : 1);
    setCellFormat(ws2, XLSX.utils.encode_cell({ r, c: 1 }), energyFmt);
  }
  if (summary.totalCostKr != null) {
    setCellFormat(ws2, XLSX.utils.encode_cell({ r: summaryRows.length - 1, c: 1 }), moneyFmt);
  }

  // ── Workbook ──────────────────────────────────────────────────
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws1, isEn ? "Drive Log" : "Körjournal");
  XLSX.utils.book_append_sheet(wb, ws2, isEn ? "Summary" : "Sammanst.");

  return XLSX.write(wb, { type: "array", bookType: "xlsx" }) as Uint8Array;
}
